baseURL = "https://elementaryai.github.io"
languageCode = "en-us"
title = "Elementary AI"
theme = "beautifulhugo"
sectionPagesMenu = "main"

[Params]
  logo = "img/eai-logo.png"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"